version: '3'

dotenv: ['.env']

tasks:

  init:
    desc: init repo
    cmds:
      - task: init:pre-commit
      - task: install

  install:
    desc: Install dependencies
    cmds:
      - uv sync

  init:pre-commit:
    desc: Install pre-commit hooks
    cmds:
      - uv add pre-commit --dev
      - uv run pre-commit install --hook-type commit-msg



  cli-create-catalog-local:
    desc: create local memory quickstart_catalog
    dir: ../polaris
    cmds:
      - |
        ./polaris \
        --client-id ${CLIENT_ID} \
        --client-secret ${CLIENT_SECRET} \
        catalogs \
        create \
        --storage-type FILE \
        --default-base-location ${DEFAULT_BASE_LOCATION} \
        quickstart_catalog

  cli-create-principal:
    desc: create a principal that has access to manage that catalog
    dir: ../polaris
    cmds:
      - |
        ./polaris \
        --client-id ${CLIENT_ID} \
        --client-secret ${CLIENT_SECRET} \
        principals \
        create \
        quickstart_user
      - |
        ./polaris \
        --client-id ${CLIENT_ID} \
        --client-secret ${CLIENT_SECRET} \
        principal-roles \
        create \
        quickstart_user_role
      - |
        ./polaris \
        --client-id ${CLIENT_ID} \
        --client-secret ${CLIENT_SECRET} \
        catalog-roles \
        create \
        --catalog quickstart_catalog \
        quickstart_catalog_role

  cli-grant-roles:
    desc: we grant the principal the principal role we created, and grant the catalog role the principal role we created.
    cmds:
      - |
        ./polaris \
        --client-id ${CLIENT_ID} \
        --client-secret ${CLIENT_SECRET} \
        principal-roles \
        grant \
        --principal quickstart_user \
        quickstart_user_role
      - |
        ./polaris \
        --client-id ${CLIENT_ID} \
        --client-secret ${CLIENT_SECRET} \
        catalog-roles \
        grant \
        --catalog quickstart_catalog \
        --principal-role quickstart_user_role \
        quickstart_catalog_role

  cli-assign-privelege:
    desc: This grants the catalog privileges CATALOG_MANAGE_CONTENT to our catalog role
    dir: ../polaris
    cmds:
      - |
        ./polaris \
        --client-id ${CLIENT_ID} \
        --client-secret ${CLIENT_SECRET} \
        privileges \
        catalog \
        grant \
        --catalog quickstart_catalog \
        --catalog-role quickstart_catalog_role \
        CATALOG_MANAGE_CONTENT



  cli-demo-spark:
    dir: ../spark
    desc: Run spark with polaris catalog file location = spark.sql("DESCRIBE FORMATTED quickstart_table").show(false)
    cmds:
      - |
        ./bin/spark-shell \
        --packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.7.1,org.apache.hadoop:hadoop-aws:3.4.0 \
        --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions \
        --conf spark.sql.catalog.quickstart_catalog.warehouse=quickstart_catalog \
        --conf spark.sql.catalog.quickstart_catalog.header.X-Iceberg-Access-Delegation=vended-credentials \
        --conf spark.sql.catalog.quickstart_catalog=org.apache.iceberg.spark.SparkCatalog \
        --conf spark.sql.catalog.quickstart_catalog.catalog-impl=org.apache.iceberg.rest:RESTCatalog \
        --conf spark.sql.catalog.quickstart_catalog.uri=http://localhost:8181/api/catalog \
        --conf spark.sql.catalog.quickstart_catalog.credential=${PRINCIPAL_CLIENT_ID}:${PRINCIPAL_CLIENT_SECRET} \
        --conf spark.sql.catalog.quickstart_catalog.scope='PRINCIPAL_ROLE:ALL' \
        --conf spark.sql.catalog.quickstart_catalog.token-refresh-enabled=true \
        --conf spark.sql.catalog.quickstart_catalog.client.region=us-west-2


  activate-venv:
    dir: ../polaris
    cmds:
      - source polaris-venv/bin/activate

  print-env:
    dotenv: ['.env']
    cmd: env

  bootstrap-env:
    cmds:
      - export $(grep -v '^#' .envs/polaris-demo.env | xargs)

  catalogs-list:
    cmds:
      - ./polaris catalogs list

  docker:build:spark-jupyter-image:
    dir: ../
    cmds:
      - docker build -t "spark-jupyter" -f polaris-boot/polaris-spark-local/dockerfiles/Dockerfile .

  docker:build:polaris-local:
    dir: ../polaris
    cmd: ./gradlew clean :polaris-quarkus-server:assemble -Dquarkus.container-image.build=true
  docker:build:spark:
    dir: ../spark
    cmd: ./build/mvn -DskipTests clean package
  docker:build:polaris-postgres-img:
    dir: ../polaris
    cmd: |
      ./gradlew clean :polaris-quarkus-server:assemble :polaris-quarkus-admin:assemble \
       -PeclipseLinkDeps=org.postgresql:postgresql:42.7.4 \
       -Dquarkus.container-image.tag=postgres-latest \
       -Dquarkus.container-image.build=true \
       --no-build-cache


  docker:compose:up-polaris-spark-local:
    cmds:
      - docker compose -f polaris-spark-local/docker-compose.yml up
  docker:compose:up-polaris-spark-local-postgres:
    cmds:
      - docker compose -f polaris-spark-local-postgres/docker-compose.yml up

  gradle:build-polaris-postgres:
    dir: ../polaris-fork
    cmd: |
      ./gradlew :polaris-quarkus-server:assemble :polaris-quarkus-admin:assemble \
       -PeclipseLinkDeps=org.postgresql:postgresql:42.7.4 \
       -Dquarkus.container-image.tag=postgres-latest \
       -Dquarkus.container-image.build=true

  rest:get-auth-token:
    dotenv: ['.env']
    cmds:
      - |
        echo "PRINCIPAL_TOKEN=$(curl -i -X POST \
        http://localhost:8181/api/catalog/v1/oauth/tokens \
        -d "grant_type=client_credentials" \
        -d "client_id=$CLIENT_ID" \
        -d "client_secret=$CLIENT_SECRET" \
        -d "scope=PRINCIPAL_ROLE:ALL" | awk -F\" '{print $4}'| tr -d '[:space:]')" | sed -i '' "s/^PRINCIPAL_TOKEN=.*/$(cat)/" .env

  rest:create-catalog-local:
    dotenv: ['.env']
    cmds:
      - |
        curl -i -X POST -H "Authorization: Bearer $PRINCIPAL_TOKEN" -H 'Accept: application/json' -H 'Content-Type: application/json' \
        http://localhost:8181/api/management/v1/catalogs \
        -d '{
             "catalog": {
               "name": "polaris",
               "type": "INTERNAL",
               "readOnly": false,
               "properties": {
                 "default-base-location": "file:///tmp/polaris/"
               },
               "storageConfigInfo": {
                 "storageType": "FILE",
                 "allowedLocations": [
                   "file:///tmp"
                 ]
               }
             }
           }'

  rest:create-catalog-s3:
    dotenv: ['.env']
    cmds:
      - |
        curl -i -X POST -H "Authorization: Bearer $PRINCIPAL_TOKEN" -H 'Accept: application/json' -H 'Content-Type: application/json' \
        http://localhost:8181/api/management/v1/catalogs \
        -d '{"name": "polariscatalog", "type": "INTERNAL", "properties": {
              "default-base-location": "s3://my/s3/path"
          },"storageConfigInfo": {
              "roleArn": "arn:aws:iam::xxxxxxxxx:role/polaris-storage",
              "storageType": "s3",
              "allowedLocations": [
                  "s3://my/s3/path"
              ]
          } }'

  rest:list-catalogs:
    dotenv: ['.env']
    cmds:
      - |
        curl -X GET "http://localhost:8181/api/management/v1/catalogs" \
        -H "Authorization: Bearer $PRINCIPAL_TOKEN"

  rest:create-principal-user:
    dotenv: ['.env']
    cmds:
      - python utils/create-principal.py engineer $PRINCIPAL_TOKEN

  rest:list-principals:
    dotenv: ['.env']
    cmds:
      - |
        curl -X GET "http://localhost:8181/api/management/v1/principals" \
        -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
        -H "Content-Type: application/json" \

  rest:create-principal-role:
    dotenv: ['.env']
    cmds:
      - |
        curl -X POST "http://localhost:8181/api/management/v1/principal-roles" \
          -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"principalRole": {"name": "engineer-role"}}'

  rest:bootstrap-hr:
    dotenv: ['.env']
    cmds:
      - echo "Creating hr-principal..."
      - |
        curl -X POST "http://localhost:8181/api/management/v1/principals" \
        -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{"name": "hr", "type": "user"}'
      - echo "Creating read-only-principal-role..."
      - |
        curl -X POST "http://localhost:8181/api/management/v1/principal-roles" \
          -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"principalRole": {"name": "hr-role"}}'

      - echo "Assigning hr-role to principals..."
      - |
        curl -X PUT "http://localhost:8181/api/management/v1/principals/engineer/principal-roles" \
          -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"principalRole": {"name": "hr-role"}}'
      - |
        curl -X PUT "http://localhost:8181/api/management/v1/principals/hr/principal-roles" \
          -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"principalRole": {"name": "hr-role"}}'

      - echo "Creating read-only-catalog-role..."
      - |
        curl -X POST "http://localhost:8181/api/management/v1/catalogs/polariscatalog/catalog-roles" \
            -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"catalogRole": {"name": "read-only-catalog-role"}}'

      - echo "Assigning read-only-catalog-role to read-only-principal-role..."
      - |
        curl -X PUT "http://localhost:8181/api/management/v1/principal-roles/hr-role/catalog-roles/polariscatalog" \
        -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{"catalogRole": {"name": "read-only-catalog-role"}}'

      - echo "Granting read-only-catalog-role CATALOG_READ_PROPERTIES..."
      - |
        curl -X PUT "http://localhost:8181/api/management/v1/catalogs/polariscatalog/catalog-roles/read-only-catalog-role/grants" \
          -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"grant": {"type": "catalog", "privilege": "TABLE_LIST"}}'
      - |
        curl -X PUT "http://localhost:8181/api/management/v1/catalogs/polariscatalog/catalog-roles/read-only-catalog-role/grants" \
          -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"grant": {"type": "catalog", "privilege": "TABLE_READ_PROPERTIES"}}'
      - |
        curl -X PUT "http://localhost:8181/api/management/v1/catalogs/polariscatalog/catalog-roles/read-only-catalog-role/grants" \
          -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"grant": {"type": "catalog", "privilege": "TABLE_READ_DATA"}}'
      - |
        curl -X PUT "http://localhost:8181/api/management/v1/catalogs/polariscatalog/catalog-roles/read-only-catalog-role/grants" \
          -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"grant": {"type": "catalog", "privilege": "VIEW_LIST"}}'
      - |
        curl -X PUT "http://localhost:8181/api/management/v1/catalogs/polariscatalog/catalog-roles/read-only-catalog-role/grants" \
          -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"grant": {"type": "catalog", "privilege": "VIEW_READ_PROPERTIES"}}'
      - |
        curl -X PUT "http://localhost:8181/api/management/v1/catalogs/polariscatalog/catalog-roles/read-only-catalog-role/grants" \
          -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"grant": {"type": "catalog", "privilege": "NAMESPACE_READ_PROPERTIES"}}'
      - |
        curl -X PUT "http://localhost:8181/api/management/v1/catalogs/polariscatalog/catalog-roles/read-only-catalog-role/grants" \
          -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"grant": {"type": "catalog", "privilege": "NAMESPACE_LIST"}}'
      - |
        curl -X PUT "http://localhost:8181/api/management/v1/catalogs/polariscatalog/catalog-roles/read-only-catalog-role/grants" \
          -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"grant": {"type": "catalog", "privilege": "LOAD_NAMESPACE_METADATA"}}'

  rest:list-grants-for-catalog-role:
    dotenv: ['.env']
    cmds:
      - |
        curl -X GET "http://localhost:8181/api/management/v1/catalogs/polariscatalog/catalog-roles/$CATALOG_ROLE/grants" \
        -H "Authorization: Bearer $PRINCIPAL_TOKEN"
    env:
      CATALOG_ROLE: read-only-catalog-role

  rest:list-catalog-roles-for-principal-role:
    dotenv: ['.env']
    cmds:
      - |
        curl -X GET "http://localhost:8181/api/management/v1/principal-roles/$PRINCIPAL_ROLE/catalog-roles/$CATALOG" \
        -H "Authorization: Bearer $PRINCIPAL_TOKEN"
    env:
      PRINCIPAL_ROLE: hr-role
      CATALOG: polariscatalog



  rest:assign-principal-role:
    dotenv: ['.env']
    cmds:
      - |
        curl -X PUT "http://localhost:8181/api/management/v1/principals/engineer/principal-roles" \
          -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"principalRole": {"name": "engineer-role"}}'

  rest:create-catalog-role:
    dotenv: ['.env']
    cmds:
      - |
        curl -X POST "http://localhost:8181/api/management/v1/catalogs/polaris/catalog-roles" \
          -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"catalogRole": {"name": "engineer-catalog-role"}}'

  rest:assign-catalog-role:
    dotenv: ['.env']
    cmds:
      - |
        curl -X PUT "http://localhost:8181/api/management/v1/principal-roles/engineer-role/catalog-roles/polaris" \
        -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{"catalogRole": {"name": "engineer-catalog-role"}}'

  rest:grant-catalog-role-privelege:
    dotenv: ['.env']
    cmds:
      - |
        curl -X PUT "http://localhost:8181/api/management/v1/catalogs/polaris/catalog-roles/engineer-catalog-role/grants" \
          -H "Authorization: Bearer $PRINCIPAL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"grant": {"type": "catalog", "privilege": "CATALOG_MANAGE_CONTENT"}}'

  rest:bootsrap-engineer:
     dotenv: ['.env']
     cmds:
       - task rest:get-auth-token
       - task rest:create-catalog-local
       - task rest:create-principal-user
       - task rest:create-principal-role
       - task rest:assign-principal-role
       - task rest:create-catalog-role
       - task rest:assign-catalog-role
       - task rest:grant-catalog-role-privelege
