services:
  polaris:
    # IMPORTANT: the image MUST contain the Postgres JDBC driver and EclipseLink dependencies, see README for instructions
    image: apache/polaris
    container_name: polaris
    ports:
      # API port
      - "8181:8181"
      # Management port (metrics and health checks)
      - "8182:8182"
      # Optional, allows attaching a debugger to the Polaris JVM
      - "5005:5005"
    volumes:
      - ./icebergdata:/data
    environment:
      JAVA_DEBUG: "true"
      JAVA_DEBUG_PORT: "*:5005"
      polaris.realm-context.realms: POLARIS
      quarkus.otel.sdk.disabled: "true"
      QUARKUS_LOG_LEVEL: DEBUG
      HADOOP_HOME: /home/polaris/hadoop
      hadoop.home.dir: /home/polaris/hadoop
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8182/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - iceberg_net
    secrets:
      - engineer_client_id
      - engineer_client_secret
      - hr_client_id
      - hr_client_secret
    # Create hadoop folder and export variable
    command: >
      bash -c "
        mkdir -p /home/polaris/hadoop &&
        export HADOOP_HOME=/home/polaris/hadoop &&
        java -jar /deployments/quarkus-run.jar"
secrets:
  engineer_client_id:
    file: ../secrets/engineer-client-id
  engineer_client_secret:
    file: ../secrets/engineer-client-secret
  hr_client_id:
    file: ../secrets/hr-client-id
  hr_client_secret:
    file: ../secrets/hr-client-secret

networks:
  iceberg_net:
